server {
    listen 443 ssl;
    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    error_page 497 301 =301 https://$host:5173$request_uri;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://payment-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
